packages:
  - 'packages/*'
  - 'packages/configs/*'
  - 'examples/*'
  - 'docs'

allowBuilds:
  '@apollo/protobufjs': true
  '@parcel/watcher': true
  '@scarf/scarf': false
  esbuild: true
  sharp: true
  unrs-resolver: true
